import java.util.Random;
import java.util.Scanner;
import java.io.*;
/*
This is one of the most basic methods to generate a random number.
next = (a*cur + b) % n
Give the next five pseudorandomnumbers generated by the process describedon page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
-27
-31
-91
65
97
*/

class pseudoRandomNumberGenerator{
    public static void main(String[] args) {
        Random rand = new Random(92);               
        int next = (12*rand.nextInt() + 5) % 100;
        System.out.println(next);
        next = (12*rand.nextInt() + 5) % 100;
        System.out.println(next); 
        next = (12*rand.nextInt() + 5) % 100;
        System.out.println(next); 
        next = (12*rand.nextInt() + 5) % 100;
        System.out.println(next); 
        next = (12*rand.nextInt() + 5) % 100;
        System.out.println(next); 
            

        
       
    }    


}